### ISSUE TITLE
Opt-in null safety

### ISSUE THREAD

**Issue by firatcetiner** [shana0440/localization_generator#3]
@shana0440 Are you planning to migrate this package to null-safety? Because I have already tried that and it seems to work. The only caveat is that the project that uses this package should also opt-in null safety since the generated `localization.dart` requires non-nullable language features. What are your thoughts? Should I open a PR?

**Comment by firatcetiner** [comment]
> @shana0440 Are you planning to migrate this package to null-safety? Because I have already tried that and it seems to work. The only caveat is that the project that uses this package should also opt-in null safety since the generated `localization.dart` requires non-nullable language features. What are your thoughts? Should I open a PR?

**Comment by firatcetiner** [comment]
> @shana0440 Are you planning to migrate this package to null-safety? Because I have already tried that and it seems to work. The only caveat is that the project that uses this package should also opt-in null safety since the generated `localization.dart` requires non-nullable language features. What are your thoughts? Should I open a PR?

**Comment by shana0440** [comment]
@firatcetiner I plan to migrate this package to null-safety and release a formal version in April, however, PR  is welcome.
